### ISSUE TITLE
Update to use slinky 0.2.0

### ISSUE THREAD

**Issue by matthewpflueger** [apollographql/react-apollo-scalajs#1]
Would really like to use this with the latest slinky release! Happy to provide a PR if you'd give a couple of pointers on what needs to be done...

**Comment by shadaj** [comment]
The changes shouldn't be too big, just need to replace `Component` with `ComponentWrapper`. Might want to wait on making a PR for a couple of days though, Slinky 0.3.0 is coming soon!
